/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // t utorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  docs: [
    "README",
    {
      type: "category",
      label: "Usage",
      items: [
        "usage/otto",
        "usage/otto_config",
        "usage/otto_ask",
        "usage/otto_chat",
        "usage/otto_cmd",
        "usage/otto_commit",
        "usage/otto_edit",
        "usage/otto_pr",
        "usage/otto_docs",
        "usage/otto_prompt",
        "usage/otto_version",
      ],
    },
  ],
};

module.exports = sidebars;
